---
kind: pipeline
name: default
type: kubernetes


trigger:
  branch:
    - master

steps:
  - name: setup
    pull: if-not-exists
    image: node:24
    commands:
      - yarn install --frozen-lockfile
    when:
      branch: master
      event: [push, pull_request]

  - name: linting
    pull: if-not-exists
    image: node:24
    commands:
      - yarn run test:lint
    when:
      branch: master
      event: [push, pull_request]

