matrix:
  NAME:
    - ukhomeofficedigital/ms-schema
  MAJOR:
    - 1
  MINOR:
    - 1
  PATCH:
    - 0
  DOCKER_USERNAME:
    - ukhomeofficedigital+ms_schema
  DOCKER_REPO:
    - quay.io
pipeline:
  build_app:
    image: docker
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker build -t ms-schema .
    when:
      event: pull_request

  docker-build-and-push:
    image: ukhomeoffice/drone-docker
    secrets: [ docker_password ]
    username: '${DOCKER_USERNAME}'
    repo: '${DOCKER_REPO}/${NAME}'
    registry: '${DOCKER_REPO}'
    tags:
      - '${MAJOR}.${MINOR}.${PATCH}-${DRONE_BUILD_NUMBER}-${DRONE_COMMIT:0:10}'
      - '${MAJOR}.${MINOR}.${PATCH}'
      - '${MAJOR}.${MINOR}'
      - '${MAJOR}'
      - 'latest'
    when:
      event: push
      branch: master
