---
kind: pipeline
name: default
type: kubernetes

environment:
  APP_NAME: ms-schema
  IMAGE_URL: quay.io/ukhomeofficedigital
  IMAGE_REPO: ms-schema
  GIT_REPO: UKHomeOffice/ms-schema

trigger:
  branch:
    - feature/*
    - master

sonar_scanner: &sonar_scanner
  pull: if-not-exists
  image: quay.io/ukhomeofficedigital/sonar-scanner-node:549b75f593f28da1c4a0a6f79877ec69d3b21037
  commands:
    - sonar-scanner -Dproject.settings=./sonar-project.properties

steps:
  - name: setup_deploy
    pull: if-not-exists
    image: node:14
    commands:
      - npm ci
    when:
      branch: 
        include:
        - master
      event: push

  - name: sonar_scanner_deploy
    <<: *sonar_scanner
    when:
      branch:
        include:
          - master
      event: push

  - name: build_image
    image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind
    commands:
      - n=0; while [ "$n" -lt 60 ] && [ ! docker stats --no-stream ]; do n=$(( n + 1 )); sleep 1; done
      - docker build --no-cache -t $${IMAGE_REPO}:$${DRONE_COMMIT_SHA} .
    volumes:
      - name: dockersock
        path: /var/run
    when:
      branch: master
      event: [push, pull_request]
  
  - name: image_to_quay
    pull: if-not-exists
    image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind
    environment:
      DOCKER_PASSWORD:
        from_secret: DOCKER_PASSWORD
    commands:
    - docker login -u="ukhomeofficedigital+drone" -p=$${DOCKER_PASSWORD} quay.io
    - docker tag $${IMAGE_REPO}:$${DRONE_COMMIT_SHA} $${IMAGE_URL}/$${IMAGE_REPO}:$${DRONE_COMMIT_SHA}
    - docker push $${IMAGE_URL}/$${IMAGE_REPO}:$${DRONE_COMMIT_SHA}
    when:
      branch: master
      event: [push, pull_request]

  - name: sonar_scanner_pr
    <<: *sonar_scanner
    when:
      branch:
        include:
          - master
          - feature/*
      event: pull_request

  # Snyk & Anchore security scans which run after branch deployment to prevent blocking of PR UAT tests
  - name: snyk_scan
    pull: if-not-exists
    image: node:14
    environment:
      SNYK_TOKEN:
        from_secret: snyk_token
    commands:
      - yarn run test:snyk
    when:
      branch:
        include:
          - master
          - feature/*
      event: pull_request

  - name: anchore_scan
    image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/anchore-submission:latest
    pull: always
    environment:
      IMAGE_NAME: gro-form:${DRONE_COMMIT_SHA}
      LOCAL_IMAGE: true
      TOLERATE: medium
      WHITELIST_FILE: hof-services-config/General_Registrars_Office/anchore-cve-exceptions.txt
    when:
      branch: master
      event: pull_request

services:
  - name: docker
    image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind

  # Anchore scanning needs background service to run
  - name: anchore-submission-server
    image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/anchore-submission:latest
    pull: always
    commands:
      - /run.sh server

# - name: build_app
#   pull: if-not-exists
#   image: docker
#   commands:
#   - docker build -t ms-schema .
#   environment:
#     DOCKER_HOST: tcp://172.17.0.1:2375
#   when:
#     event:
#     - pull_request

# - name: docker-build-and-push
#   pull: if-not-exists
#   image: ukhomeoffice/drone-docker
#   settings:
#     registry: quay.io
#     repo: quay.io/ukhomeofficedigital/ms-schema
#     tags:
#     - 1.1.0-${DRONE_BUILD_NUMBER}-${DRONE_COMMIT:0:10}
#     - 1.1.0
#     - 1.1
#     - 1
#     - latest
#     username: ukhomeofficedigital+ms_schema
#   environment:
#     DOCKER_PASSWORD:
#       from_secret: docker_password
#   when:
#     branch:
#     - master
#     event:
#     - push

...
